// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBILvOnuY8fu-IE5TvkCUoJ6kSTQlClaRw',
    appId: '1:232566600549:web:3882901a27b6cd874d278c',
    messagingSenderId: '232566600549',
    projectId: 'agriculture-inventory-manage',
    authDomain: 'agriculture-inventory-manage.firebaseapp.com',
    storageBucket: 'agriculture-inventory-manage.firebasestorage.app',
    measurementId: 'G-DDN93C41NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETGisbaKO1mbmWxG1VwUdGq1NjvG6Qik',
    appId: '1:232566600549:android:ca9154572679ea774d278c',
    messagingSenderId: '232566600549',
    projectId: 'agriculture-inventory-manage',
    storageBucket: 'agriculture-inventory-manage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2pDuZvb2Yx7iUp5H0-m_IIFj9uGl_8f0',
    appId: '1:232566600549:ios:6e5ed34ab2f31d264d278c',
    messagingSenderId: '232566600549',
    projectId: 'agriculture-inventory-manage',
    storageBucket: 'agriculture-inventory-manage.firebasestorage.app',
    iosBundleId: 'com.example.agricultureInventoryManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2pDuZvb2Yx7iUp5H0-m_IIFj9uGl_8f0',
    appId: '1:232566600549:ios:6e5ed34ab2f31d264d278c',
    messagingSenderId: '232566600549',
    projectId: 'agriculture-inventory-manage',
    storageBucket: 'agriculture-inventory-manage.firebasestorage.app',
    iosBundleId: 'com.example.agricultureInventoryManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBILvOnuY8fu-IE5TvkCUoJ6kSTQlClaRw',
    appId: '1:232566600549:web:272b742d23598d0c4d278c',
    messagingSenderId: '232566600549',
    projectId: 'agriculture-inventory-manage',
    authDomain: 'agriculture-inventory-manage.firebaseapp.com',
    storageBucket: 'agriculture-inventory-manage.firebasestorage.app',
    measurementId: 'G-HP1VS2VMVK',
  );
}
